# Extract integer/float constants from src/engine/core/engine_config.h and
# emit them as a GLSL header at shaders/_generated/engine_config.glsl.
#
# This makes engine_config.h the single source of truth for cross-language
# constants (MAX_LIGHTS et al) that today are duplicated by hand in the
# shaders. Shaders can keep their explicit `const int MAX_LIGHTS = 32;`
# lines for now; once vkmGL gains shader-include support they should be
# replaced by `#include "_generated/engine_config.glsl"`.
#
# Inputs:  src/engine/core/engine_config.h
# Outputs: shaders/_generated/engine_config.glsl

set(_engine_config_h ${CMAKE_SOURCE_DIR}/src/engine/core/engine_config.h)
set(_generated_glsl  ${CMAKE_SOURCE_DIR}/shaders/_generated/engine_config.glsl)

file(READ ${_engine_config_h} _config_src)

# Each capture is (C++ name, GLSL type, GLSL name). We grep one regex per
# constant rather than parse C++ properly - keeps this script trivial.
function(_extract_uint cxx_name out_var)
    string(REGEX MATCH "constexpr[ \t]+uint32_t[ \t]+${cxx_name}[ \t]*=[ \t]*([0-9]+)" _ "${_config_src}")
    set(${out_var} ${CMAKE_MATCH_1} PARENT_SCOPE)
endfunction()
function(_extract_float cxx_name out_var)
    string(REGEX MATCH "constexpr[ \t]+float[ \t]+${cxx_name}[ \t]*=[ \t]*([^;]+);" _ "${_config_src}")
    set(${out_var} ${CMAKE_MATCH_1} PARENT_SCOPE)
endfunction()

_extract_uint(MAX_LIGHTS              _max_lights)
_extract_uint(MAX_SHADOW_CASTERS_2D   _max_shadow_2d)
_extract_uint(MAX_SHADOW_CASTERS_CUBE _max_shadow_cube)
_extract_uint(NUM_CASCADES            _num_cascades)
_extract_float(SHADOW_CUBE_NEAR       _cube_near)
_extract_float(FIXED_TIME_STEP        _fixed_step)

if(NOT _max_lights OR NOT _max_shadow_2d OR NOT _max_shadow_cube OR NOT _num_cascades OR NOT _cube_near)
    message(FATAL_ERROR "generate_shader_config: failed to extract a constant from ${_engine_config_h}")
endif()

# Mirror the C++ defaults to GLSL.
set(_glsl
"// AUTO-GENERATED by cmake/generate_shader_config.cmake at configure time.
// Source of truth: src/engine/core/engine_config.h
//
// Do not edit by hand - any change will be overwritten next configure.
// Once vkmGL supports shader-side #include, the inline `const int MAX_LIGHTS`
// declarations in shaders/pbr/fragment.shader can be deleted and this
// file included instead.

const int   MAX_LIGHTS              = ${_max_lights};
const int   SHADOW_MAX_CASTERS_2D   = ${_max_shadow_2d};
const int   SHADOW_MAX_CASTERS_CUBE = ${_max_shadow_cube};
const int   NUM_CASCADES            = ${_num_cascades};
const float SHADOW_CUBE_NEAR        = ${_cube_near};
")

file(WRITE ${_generated_glsl} "${_glsl}")
message(STATUS "Generated ${_generated_glsl} (MAX_LIGHTS=${_max_lights}, NUM_CASCADES=${_num_cascades})")
