# Extract integer/float constants from src/engine/core/engine_config.h and
# emit them as a GLSL header at shaders/_generated/engine_config.glsl.
#
# This makes engine_config.h the single source of truth for cross-language
# constants (MAX_LIGHTS et al). The forward shaders currently hand-define these
# (the shader #include preprocessor is not yet wired into the compile path), so
# this script also GUARDS against drift: it fails configure if a shader's
# hardcoded MAX_LIGHTS diverges from engine_config.h. A silent mismatch would be
# a std140 UBO-array size mismatch (out-of-bounds reads) at runtime.
#
# Inputs:  src/engine/core/engine_config.h
# Outputs: shaders/_generated/engine_config.glsl

set(_engine_config_h ${CMAKE_SOURCE_DIR}/src/engine/core/engine_config.h)
set(_generated_glsl  ${CMAKE_SOURCE_DIR}/shaders/_generated/engine_config.glsl)

file(READ ${_engine_config_h} _config_src)

# Each capture is (C++ name, GLSL type, GLSL name). We grep one regex per
# constant rather than parse C++ properly - keeps this script trivial.
function(_extract_uint cxx_name out_var)
    string(REGEX MATCH "constexpr[ \t]+uint32_t[ \t]+${cxx_name}[ \t]*=[ \t]*([0-9]+)" _ "${_config_src}")
    set(${out_var} ${CMAKE_MATCH_1} PARENT_SCOPE)
endfunction()
function(_extract_float cxx_name out_var)
    string(REGEX MATCH "constexpr[ \t]+float[ \t]+${cxx_name}[ \t]*=[ \t]*([^;]+);" _ "${_config_src}")
    set(${out_var} ${CMAKE_MATCH_1} PARENT_SCOPE)
endfunction()

_extract_uint(MAX_LIGHTS              _max_lights)
_extract_uint(MAX_SHADOW_CASTERS_2D   _max_shadow_2d)
_extract_uint(MAX_SHADOW_CASTERS_CUBE _max_shadow_cube)
_extract_uint(NUM_CASCADES            _num_cascades)
_extract_float(SHADOW_CUBE_NEAR       _cube_near)
_extract_float(FIXED_TIME_STEP        _fixed_step)

if(NOT _max_lights OR NOT _max_shadow_2d OR NOT _max_shadow_cube OR NOT _num_cascades OR NOT _cube_near)
    message(FATAL_ERROR "generate_shader_config: failed to extract a constant from ${_engine_config_h}")
endif()

# Drift guard: the forward shaders hand-define MAX_LIGHTS (they don't #include
# the generated header yet). Fail configure if any drifts from engine_config.h,
# so a UBO-array size mismatch can never ship silently. Drop this once the
# shaders #include _generated/engine_config.glsl through the shader preprocessor.
set(_forward_shaders
    ${CMAKE_SOURCE_DIR}/shaders/forward/pbr/fragment.shader
    ${CMAKE_SOURCE_DIR}/shaders/forward/phong/fragment.shader
)
foreach(_shader ${_forward_shaders})
    if(EXISTS ${_shader})
        file(READ ${_shader} _shader_src)
        if(_shader_src MATCHES "#define[ \t]+MAX_LIGHTS[ \t]+([0-9]+)")
            if(NOT CMAKE_MATCH_1 STREQUAL _max_lights)
                message(FATAL_ERROR
                    "Shader/engine constant drift: ${_shader} hardcodes MAX_LIGHTS="
                    "${CMAKE_MATCH_1} but engine_config.h has ${_max_lights}. Update the "
                    "shader's #define (or #include _generated/engine_config.glsl).")
            endif()
        endif()
    endif()
endforeach()

# Mirror the C++ defaults to GLSL.
set(_glsl
"// AUTO-GENERATED by cmake/generate_shader_config.cmake at configure time.
// Source of truth: src/engine/core/engine_config.h
//
// Do not edit by hand - any change will be overwritten next configure.
// The forward shaders currently hand-define these constants; a configure-time
// check in generate_shader_config.cmake keeps them from drifting from this file.

const int   MAX_LIGHTS              = ${_max_lights};
const int   MAX_SHADOW_CASTERS_2D   = ${_max_shadow_2d};
const int   MAX_SHADOW_CASTERS_CUBE = ${_max_shadow_cube};
const int   NUM_CASCADES            = ${_num_cascades};
const float SHADOW_CUBE_NEAR        = ${_cube_near};
")

file(WRITE ${_generated_glsl} "${_glsl}")
message(STATUS "Generated ${_generated_glsl} (MAX_LIGHTS=${_max_lights}, NUM_CASCADES=${_num_cascades})")
